name: Bug 鍙嶉
description: 鎻忚堪浣犳墍閬囧埌鐨刡ug
labels: [ "bug" ]
title: "[Bug] "
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 妫€鏌ユ竻鍗?      options:
        - label: 鎼滅储浜?[鍘嗗彶 issue](https://github.com/sxd91/qiliquid/issues?q=is%3Aissue) 锛屽苟鏈彂鐜扮浉鍚岄棶棰?          required: true
        - label: 姝ｅ湪浣跨敤鏈€鏂扮増鏈€?          required: true
        - label: 宸叉帓闄ょ綉缁滈棶棰?          required: true
        - label: 宸叉帓闄よ处鍙烽棶棰?          required: true
        - label: 宸叉帓闄よ缃棶棰?          required: true
  
  - type: checkboxes
    id: assign
    attributes:
      label: Assign
      options:
        - label: self-assign
          required: false

  - type: textarea
    id: version
    attributes:
      label: 鐗堟湰鍙?    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 澶嶇幇姝ラ
      description: 璇锋彁渚涘鐜拌闂鎵€闇€鐨勫叿浣撴楠ゃ€?    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 棰勬湡琛屼负
      description: 璇锋弿杩颁綘鏈熸湜鐨勬纭涓烘垨缁撴灉銆?    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 瀹為檯琛屼负
      description: 璇锋弿杩板疄闄呯殑琛屼负鎴栫粨鏋溿€?    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 閿欒鏃ュ織
      description: 璇锋彁渚涜缃?>鍏充簬->閿欒鏃ュ織涓殑鍐呭锛岀矘璐村湪涓嬫柟浠ｇ爜妗嗕腑銆傚鏋滄病鏈夛紝璇锋彁渚涙偍鐨刟pp鐗堟湰鍙枫€佺郴缁熺増鏈€佽澶囧瀷鍙风瓑鐩稿叧淇℃伅銆?
  - type: textarea
    id: info
    attributes:
      label: 鐩稿叧淇℃伅
      description: 璇疯ˉ鍏呮埅鍥俱€佸綍灞忋€丅V鍙风瓑鍏朵粬鏈夊姪浜庤В鍐抽棶棰樼殑淇℃伅銆?
