name: 鍔熻兘璇锋眰
description: 瀵逛簬鍔熻兘鐨勪竴浜涘缓璁?labels: [ "enhancement" ]
title: "[FR] "
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: 妫€鏌ユ竻鍗?      options:
        - label: 鎼滅储浜?[鍘嗗彶 issue](https://github.com/sxd91/qiliquid/issues?q=is%3Aissue) 锛屽苟鏈彂鐜扮浉鍚屽姛鑳借姹?          required: true
        - label: 姝ｅ湪浣跨敤鏈€鏂扮増鏈€?          required: true
        - label: 璁剧疆涓湭鎼滅储鍒拌鍔熻兘
          required: true

  - type: checkboxes
    id: assign
    attributes:
      label: Assign
      options:
        - label: self-assign
          required: false

  - type: textarea
    id: desc
    attributes:
      label: 鍔熻兘鎻忚堪
      description: 璇锋彁渚涘鎵€璇锋眰鍔熻兘鐨勬竻鏅版弿杩般€?    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 瑙ｅ喅鏂规
      description: 濡傛灉浣犳湁浠讳綍鍏充簬濡備綍瀹炵幇杩欎釜鍔熻兘鐨勬兂娉曟垨寤鸿锛岃鍦ㄨ繖閲屾彁渚涖€?
  - type: textarea
    id: addition
    attributes:
      label: 鍏朵粬
      description: 璇锋彁渚涘凡瀹炵幇璇ュ姛鑳芥垨绫讳技鍔熻兘鐨勫簲鐢?
