script_template: inno_setup.iss
# AppId 鐨勫€煎敮涓€鏍囪瘑姝ゅ簲鐢ㄣ€?# 涓嶈鍦ㄥ叾浠栧簲鐢ㄧ殑瀹夎绋嬪簭涓娇鐢ㄧ浉鍚岀殑 AppId 鍊笺€?app_id: 5ef970f9-2b9e-4155-b7d6-a9d4dbd6b226
publisher: dom
publisher_url: https://github.com/sxd91/qiliquid
display_name: LiqLiquid
# create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# 杩欓噷鐨勮矾寰勬槸鐩稿浜庨」鐩牴鐩綍鐨勮矾寰勶紱 鍥炬爣鏍煎紡蹇呴』鏄痠co鏍煎紡锛屼笉鑳芥槸png鎴栧叾瀹?setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - zh
privileges_required: admin

